codersforcauses/wajo

client/style-guide.md
Introduce a comprehensive style guide outlining conventions and best practices for project styling, including guidelines for JavaScript, CSS, and component structure.
=> Add project styling guide and best practices

.github/workflows/ci-backend.yml
Apply fix from https://github.com/codersforcauses/coexist/pull/114/files#diff-d534d457d2f453ff292b326309bebf3d6b2f7e067ca4247038b61df22d09c728
=> Fix deps caching error

client/src/pages/_app.tsx, client/tailwind.config.ts
**[Briefly summarise the changes that you made. Just high-level stuff]**
- Resolve #46
=> added roboto font and changed bg color to white

server/api/auth/serializers.py, server/api/auth/urls.py, server/api/auth/views.py, server/api/users/serializers.py, server/api/users/views.py
includes several updates to the authentication and user management functionality, focusing on enhancing role-based access control and improving data handling in serializers and views. 
* **Custom Token Serializer Updates**: The `CustomTokenObtainPairSerializer` now includes `school_id` and `sub_id` in the token payload for users with roles of student or teacher.
* **View and URL Adjustments**: The `CustomTokenObtainPairView` is introduced to replace the `CustomTokenObtainPairSerializer` in the authentication URL configuration. [[1]](diffhunk://#diff-828c7a979e9fc2d3b5cd556baac0d8c091ce779d5971141d7bfff4a80a8a2e63L17-R20) [[2]](diffhunk://#diff-3c32c25e18c495698d5ac18778a49c53a058bf89ca066be231914557e19d3b39L5-R5)
* **Username Generation**: Adjusted the logic for generating the `username` …
=> 103 wrap school id info and some teacher or student id into the jwt token paypload

server/api/users/admin.py, server/api/users/models.py, server/api/users/serializers.py, server/api/users/views.py
**add several fields in school model and also adjustment in the relevant views and serializer**
- Resolve #107
=> Issue 107 rebuild for the issue 77

client/src/components/ui/Users/data-table-form.tsx, client/src/types/user.ts
Several Updates
1 add the random password generator
2 function to export the csv
Still need to discuss with team members and make change on the create page to make it fit the model in the backend
- Resolve #118
=> Issue 118 password saving feature

client/src/components/ui/Question/preview-modal.tsx, client/src/pages/question/[id].tsx, client/src/pages/question/create.tsx
- Fix image dimensions to ensure proper display
- Resolve issue where images were not showing in question update forms
- Correct the update logic for the "layout" data field
- [Y] The pull request title has an issue number
- [Y] The change works by "Smoke testing" or quick testing
- [N] The change has tests
- [N] The change has documentation
Screenshot
- Resolve #135
=> Issue 135 - Hotfix Invalid Image Dimensions & Update Bug

client/src/components/ui/app-sidebar.tsx
simplify menu toggle logic and enhance sidebar styling
- [Y] The pull request title has an issue number
- [Y] The change works by "Smoke testing" or quick testing
- [N] The change has tests
- [N] The change has documentation
Screenshot
- Resolve #146
=> Issue 146 Improve Sidebar Behavior

client/src/components/layout.tsx, client/src/components/ui/Users/data-grid.tsx, client/src/context/auth-provider.tsx, client/src/pages/dashboard/users/staffs/[id].tsx, client/src/pages/dashboard/users/staffs/index.tsx, client/src/pages/dashboard/users/students/[id].tsx, client/src/pages/dashboard/users/teachers/[id].tsx, client/src/pages/dashboard/users/teachers/index.tsx, client/src/types/user.ts
Create individual edit pages for:
- Staff
- Teacher
- Student
- [Y] The pull request title has an issue number
- [Y] The change works by "Smoke testing" or quick testing
- [N] The change has tests
- [N] The change has documentation
**Screenshot**
Staff
Teacher
Student
- Resolve #148
=> Issue 148 Split User Edit Pages by Role

client/src/components/ui/Question/preview-modal.tsx, client/src/components/ui/Users/teacher-data-table-form.tsx, client/src/pages/dashboard/users/teachers/create.tsx, client/src/types/question.ts, client/src/types/user.ts, server/api/users/serializers.py, server/api/users/tests.py, server/api/users/views.py
modifying the `PreviewModal` component to render LaTeX
updating the `TeacherDataTableForm` component to handle form submissions more effectively
adding new interfaces to the `question.ts` file.
* [`client/src/components/ui/Question/preview-modal.tsx`](diffhunk://#diff-b39b1eb47e6ab527d9f130df3733edce84e3b21333231aa871d74adf7837c718L119-R119): Changed the rendering of the `solution` to use the `Latex` component for better display of LaTeX content.
* [`client/src/components/ui/Users/teacher-data-table-form.tsx`](diffhunk://#diff-a75cf004adf94c2e35e41758a2cf48488582dff57739618c865f21b865af7efbR2): Added `useQueryClient` import and initialized `queryClient` to manage query caching. Updated the `onSubmit` function to handle bulk teacher creation and query invalidation. Modified the form …
=> bug-fix(teacher): update teacher creation form and API handling

client/src/pages/dashboard/question/index.tsx
Change the button label in the dashboard to better reflect the action of creating a question instead of a quiz.
=> Update button label from "Create a Quiz" to "Create a Question"

.github/workflows/docker-build.yml, docker/client/Dockerfile
Eliminate unnecessary environment variable settings in both GitHub Actions and the Dockerfile to streamline the configuration process.
=> Remove redundant environment variable settings in GitHub Actions and Dockerfile

.github/workflows/docker-build.yml, docker/client/Dockerfile
Remove redundant environment variable settings in GitHub Actions and configure backend URL variables directly in the Dockerfile for improved clarity and efficiency.
=> Refactor Docker environment variable settings

.github/workflows/docker-build.yml
Switch environment variable references in the Dockerfile to use GitHub secrets for enhanced security.
=> Update GitHub Actions to use secrets for environment variables in Docker setup

.github/workflows/docker-build.yml, server/api/settings.py
Use secrets for environment variables in GitHub Actions and add FRONTEND_URL to CORS_ALLOWED_ORIGINS for improved configuration.
=> Update GitHub Actions and CORS settings for security and configuration

.github/workflows/docker-build.yml, server/.env.example, server/api/settings.py
Refactor the Docker build workflow to utilize variables for environment variables instead of secrets.
=> Update CORS and build workflow to use vars for environment variables

client/package-lock.json
Regenerate the package-lock.json file to ensure consistency and remove the pastpaper quiz page component to streamline the application.
=> Recreate package-lock.json and remove pastpaper quiz component

client/src/styles/globals.css
**[Briefly summarise the changes that you made. Just high-level stuff]**
=> Add min-width property to global styles for better layout control

client/src/types/quiz.ts
**[Briefly summarise the changes that you made. Just high-level stuff]**
- Resolve #178
=> mark bug fixed

client/src/components/ui/Quiz/generic-quiz.tsx, client/src/components/ui/button.tsx, client/src/pages/dashboard/profile/index.tsx, client/src/pages/dashboard/test/competition/[id].tsx, client/src/pages/quiz/index.tsx, client/src/types/quiz.ts, server/api/quiz/admin.py
**[Briefly summarise the changes that you made. Just high-level stuff]**
removed logic for localstorage of quiz answers, instead all answers are stored in db and fetched at the start of the quiz from a student's previous attempts
- Resolve #185
=> Issue 185 patches p3
